import type { ServiceRequestSummary } from "@/types/app";

export const mockServiceRequests: ServiceRequestSummary[] = [
  {
    id: "req-001",
    clientId: "client-001",
    clientName: "Famille Kouadio",
    serviceType: "Aide ménagère",
    city: "Abidjan",
    neighborhood: "Cocody",
    budget: 170000,
    frequency: "3 fois par semaine",
    urgency: "high",
    status: "under_review",
    housingPossible: false,
    requiredSkills: ["Nettoyage résidentiel", "Repassage"],
    schedule: ["Lundi matin", "Mercredi matin", "Samedi journée"],
    createdAt: "2026-06-02"
  },
  {
    id: "req-002",
    clientId: "client-002",
    clientName: "Résidence Baobab",
    serviceType: "Agent d'entretien",
    city: "Dakar",
    neighborhood: "Plateau",
    budget: 240000,
    frequency: "Temps plein",
    urgency: "medium",
    status: "matched",
    housingPossible: false,
    requiredSkills: ["Entretien bureaux", "Hygiène et sécurité"],
    schedule: ["Lundi journée", "Mardi journée", "Jeudi journée"],
    createdAt: "2026-06-05"
  },
  {
    id: "req-003",
    clientId: "client-003",
    clientName: "Famille Mensah",
    serviceType: "Cuisinière",
    city: "Cotonou",
    neighborhood: "Fidjrossè",
    budget: 230000,
    frequency: "Week-end",
    urgency: "low",
    status: "submitted",
    housingPossible: true,
    requiredSkills: ["Cuisine familiale", "Cuisine événementielle"],
    schedule: ["Vendredi journée", "Samedi journée"],
    createdAt: "2026-06-08"
  },
  {
    id: "req-004",
    clientId: "client-001",
    clientName: "Famille Kouadio",
    serviceType: "Nounou",
    city: "Abidjan",
    neighborhood: "Riviera",
    budget: 200000,
    frequency: "Temps plein",
    urgency: "high",
    status: "submitted",
    housingPossible: true,
    requiredSkills: ["Garde d'enfants", "Courses"],
    schedule: ["Lundi journée", "Mardi journée", "Mercredi journée"],
    createdAt: "2026-06-10"
  },
  {
    id: "req-005",
    clientId: "client-003",
    clientName: "Famille Mensah",
    serviceType: "Assistante à domicile",
    city: "Bamako",
    neighborhood: "ACI 2000",
    budget: 150000,
    frequency: "2 fois par semaine",
    urgency: "medium",
    status: "assigned",
    housingPossible: false,
    requiredSkills: ["Soins aux personnes âgées", "Courses"],
    schedule: ["Mardi matin", "Jeudi matin"],
    createdAt: "2026-06-11"
  }
];
